import {
  MCM_LEATHER_WIKI_CORPUS_VERSION,
  MCM_LEATHER_WIKI_RETRIEVER_VERSION,
  MCM_LEATHER_WIKI_VERSION,
} from '@/server/knowledge/mcmLeatherWiki';
import { MCM_MATERIAL_REUSE_KNOWLEDGE_VERSION } from './materialReuseKnowledge';

export const MCM_ANALYSIS_PROMPT_VERSION =
  'MCM_BAG_ANALYSIS_WIKI_GROUNDED_2026_08_21_V1';

export const MCM_ANALYSIS_KNOWLEDGE_VERSION = [
  MCM_MATERIAL_REUSE_KNOWLEDGE_VERSION,
  MCM_LEATHER_WIKI_VERSION,
  MCM_ANALYSIS_PROMPT_VERSION,
].join('|');

export const MCM_ANALYSIS_GROUNDING_COMPONENTS = {
  reuseGuideVersion: MCM_MATERIAL_REUSE_KNOWLEDGE_VERSION,
  wikiCorpusVersion: MCM_LEATHER_WIKI_CORPUS_VERSION,
  wikiRetrieverVersion: MCM_LEATHER_WIKI_RETRIEVER_VERSION,
  promptVersion: MCM_ANALYSIS_PROMPT_VERSION,
} as const;
