import {
  MCM_LEATHER_WIKI_CORPUS_VERSION,
  MCM_LEATHER_WIKI_RETRIEVAL_CORPUS_SHA256,
  MCM_LEATHER_WIKI_RETRIEVER_VERSION,
} from '@/server/knowledge/mcmLeatherWiki';
import { MCM_MATERIAL_REUSE_KNOWLEDGE_VERSION } from './materialReuseKnowledge';

export const MCM_ANALYSIS_PROMPT_VERSION =
  'MCM_BAG_ANALYSIS_WIKI_GROUNDED_V3_2026_08_24_V3';

export const MCM_ANALYSIS_KNOWLEDGE_VERSION = [
  MCM_MATERIAL_REUSE_KNOWLEDGE_VERSION,
  MCM_LEATHER_WIKI_CORPUS_VERSION,
  MCM_LEATHER_WIKI_RETRIEVER_VERSION,
  MCM_LEATHER_WIKI_RETRIEVAL_CORPUS_SHA256,
  MCM_ANALYSIS_PROMPT_VERSION,
].join('|');

export const MCM_ANALYSIS_GROUNDING_COMPONENTS = {
  promptVersion: MCM_ANALYSIS_PROMPT_VERSION,
  reuseGuideVersion: MCM_MATERIAL_REUSE_KNOWLEDGE_VERSION,
  wikiCorpusSha256: MCM_LEATHER_WIKI_RETRIEVAL_CORPUS_SHA256,
  wikiCorpusVersion: MCM_LEATHER_WIKI_CORPUS_VERSION,
  wikiRetrieverVersion: MCM_LEATHER_WIKI_RETRIEVER_VERSION,
} as const;
